# Generated by Django 3.0.1 on 2022-04-04 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_aircraft', models.CharField(max_length=100, unique=True)),
                ('modello', models.CharField(max_length=200)),
                ('stato', models.BooleanField()),
                ('km_percorsi', models.IntegerField()),
                ('posti_primaclasse', models.IntegerField()),
                ('posti_secondaclasse', models.IntegerField()),
                ('posti_economy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=100, unique=True)),
                ('type_airport', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('latitude_deg', models.CharField(max_length=30)),
                ('longitude_deg', models.CharField(max_length=30)),
                ('elevation_ft', models.IntegerField()),
                ('continent', models.CharField(max_length=100)),
                ('iso_country', models.CharField(max_length=50)),
                ('iso_region', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=100)),
                ('gps_code', models.IntegerField()),
                ('iata_code', models.CharField(max_length=30)),
                ('local_code', models.CharField(max_length=30)),
                ('cap', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(max_length=100)),
                ('address_line_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_volo', models.CharField(max_length=200, unique=True)),
                ('distanza_percorsa', models.IntegerField()),
                ('ora_partenza', models.TimeField()),
                ('ora_arrivo', models.TimeField()),
                ('data_partenza', models.DateField(default=django.utils.timezone.now)),
                ('aeroporto_arrivo', models.ForeignKey(default=-2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_arrivo', to='dashboard.Airport')),
                ('aeroporto_partenza', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_partenza', to='dashboard.Airport')),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettera', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('volo', models.ForeignKey(default='Volo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Fly')),
            ],
        ),
        migrations.CreateModel(
            name='Utent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prenotazione', models.CharField(max_length=200, unique=True)),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Posto')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Utent')),
                ('volo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Fly')),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_personale', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mansione', models.CharField(max_length=200)),
                ('ruolo', models.CharField(choices=[('Volo', 'Volo'), ('Assistenza', 'Assistenza'), ('Terra', 'Terra'), ('Terra', 'Terra')], max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Manutenzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_manutenzione', models.DateTimeField()),
                ('manutenzione_km', models.IntegerField()),
                ('manutenzione_giorni', models.IntegerField()),
                ('km_restanti', models.IntegerField()),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Aircraft')),
            ],
        ),
    ]
