# Generated by Django 3.0.1 on 2022-04-09 10:22

import dashboard.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220407_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posto',
            name='volo',
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='code_prenotazione',
            field=models.CharField(default=dashboard.utils.make_uuid, editable=False, max_length=200, unique=True),
        ),
    ]
