# Generated by Django 3.0.1 on 2022-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220409_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='classe',
            field=models.CharField(default='Economy', max_length=30),
        ),
    ]
