# Generated by Django 3.0.1 on 2022-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_fly_posti_prenotati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='posti_prenotati',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
