# Generated by Django 3.0.1 on 2022-04-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220410_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='posti_prenotati',
        ),
    ]
