# Generated by Django 3.0.1 on 2022-04-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220413_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personale',
            name='ruolo',
            field=models.CharField(choices=[('Volo', 'Volo'), ('Assistenza', 'Assistenza'), ('Terra', 'Terra')], max_length=200),
        ),
    ]
