# Generated by Django 3.0.1 on 2022-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20220421_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personale',
            name='telefono',
            field=models.CharField(max_length=40),
        ),
    ]
