# Generated by Django 3.0.1 on 2022-04-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20220422_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='posti_prenotati',
            field=models.IntegerField(default=0),
        ),
    ]
